-- set global status line
vim.o.laststatus = 3

-- set status line

local extensionTable = {
	-- Exact Match
	['gruntfile.coffee'] = '',
	['gruntfile.js'] = '',
	['gruntfile.ls'] = '',
	['gulpfile.coffee'] = '',
	['gulpfile.js'] = '',
	['gulpfile.ls'] = '',
	['mix.lock'] = '',
	['dropbox'] = '',
	['.ds_store'] = '',
	['.gitconfig'] = '',
	['.gitignore'] = '',
	['.gitlab-ci.yml'] = '',
	['.bashrc'] = '',
	['.zshrc'] = '',
	['.vimrc'] = '',
	['.gvimrc'] = '',
	['_vimrc'] = '',
	['_gvimrc'] = '',
	['.bashprofile'] = '',
	['favicon.ico'] = '',
	['license'] = '',
	['node_modules'] = '',
	['react.jsx'] = '',
	['procfile'] = '',
	['dockerfile'] = '',
	['docker-compose.yml'] = '',
	-- Extension
	['styl'] = '',
	['sass'] = '',
	['scss'] = '',
	['htm'] = '',
	['html'] = '',
	['slim'] = '',
	['ejs'] = '',
	['css'] = '',
	['less'] = '',
	['md'] = '',
	['mdx'] = '',
	['markdown'] = '',
	['rmd'] = '',
	['json'] = '',
	['js'] = '',
	['mjs'] = '',
	['jsx'] = '',
	['rb'] = '',
	['php'] = '',
	['py'] = '',
	['pyc'] = '',
	['pyo'] = '',
	['pyd'] = '',
	['coffee'] = '',
	['mustache'] = '',
	['hbs'] = '',
	['conf'] = '',
	['ini'] = '',
	['yml'] = '',
	['yaml'] = '',
	['toml'] = '',
	['bat'] = '',
	['jpg'] = '',
	['jpeg'] = '',
	['bmp'] = '',
	['png'] = '',
	['gif'] = '',
	['ico'] = '',
	['twig'] = '',
	['cpp'] = '',
	['c++'] = '',
	['cxx'] = '',
	['cc'] = '',
	['cp'] = '',
	['c'] = '',
	['cs'] = '',
	['h'] = '',
	['hh'] = '',
	['hpp'] = '',
	['hxx'] = '',
	['hs'] = '',
	['lhs'] = '',
	['lua'] = '',
	['java'] = '',
	['sh'] = '',
	['fish'] = '',
	['bash'] = '',
	['zsh'] = '',
	['ksh'] = '',
	['csh'] = '',
	['awk'] = '',
	['ps1'] = '',
	['ml'] = 'λ',
	['mli'] = 'λ',
	['diff'] = '',
	['db'] = '',
	['sql'] = '',
	['dump'] = '',
	['clj'] = '',
	['cljc'] = '',
	['cljs'] = '',
	['edn'] = '',
	['scala'] = '',
	['go'] = '',
	['dart'] = '',
	['xul'] = '',
	['sln'] = '',
	['suo'] = '',
	['pl'] = '',
	['pm'] = '',
	['t'] = '',
	['rss'] = '',
	['f#'] = '',
	['fsscript'] = '',
	['fsx'] = '',
	['fs'] = '',
	['fsi'] = '',
	['rs'] = '',
	['rlib'] = '',
	['d'] = '',
	['erl'] = '',
	['hrl'] = '',
	['ex'] = '',
	['exs'] = '',
	['eex'] = '',
	['leex'] = '',
	['vim'] = '',
	['ai'] = '',
	['psd'] = '',
	['psb'] = '',
	['ts'] = '',
	['tsx'] = '',
	['jl'] = '',
	['pp'] = '',
	['vue'] = '﵂',
	['elm'] = '',
	['swift'] = '',
	['xcplayground'] = '',
}

local modeTable = {
	['n']     = 'NORMAL',
	['no']    = 'O-PENDING',
	['nov']   = 'O-PENDING',
	['noV']   = 'O-PENDING',
	['no\22'] = 'O-PENDING',
	['niI']   = 'NORMAL',
	['niR']   = 'NORMAL',
	['niV']   = 'NORMAL',
	['nt']    = 'NORMAL',
	['ntT']   = 'NORMAL',
	['v']     = 'VISUAL',
	['vs']    = 'VISUAL',
	['V']     = 'V-LINE',
	['Vs']    = 'V-LINE',
	['\22']   = 'V-BLOCK',
	['\22s']  = 'V-BLOCK',
	['s']     = 'SELECT',
	['S']     = 'S-LINE',
	['\19']   = 'S-BLOCK',
	['i']     = 'INSERT',
	['ic']    = 'INSERT',
	['ix']    = 'INSERT',
	['R']     = 'REPLACE',
	['Rc']    = 'REPLACE',
	['Rx']    = 'REPLACE',
	['Rv']    = 'V-REPLACE',
	['Rvc']   = 'V-REPLACE',
	['Rvx']   = 'V-REPLACE',
	['c']     = 'COMMAND',
	['cv']    = 'EX',
	['ce']    = 'EX',
	['r']     = 'REPLACE',
	['rm']    = 'MORE',
	['r?']    = 'CONFIRM',
	['!']     = 'SHELL',
	['t']     = 'TERMINAL',
}

local function get_mode()
	local mode_code = vim.api.nvim_get_mode().mode
	if modeTable[mode_code] == nil then
		return mode_code
	end
	return modeTable[mode_code]
end

vim.opt.statusline:append(' ')
vim.opt.statusline:append(get_mode())
vim.opt.statusline:append("%f")
