#! /bin/sh

# Variables To Modify
PRIMARY_COLOR="#00acc1"
INACTIVE_COLOR="#757575"

# lauching sxhkd
sxhkd &

# launch picom
picom --config ~/.config/picom/picom.conf &

# Color
bspc config active_border_color $PRIMARY_COLOR
bspc config normal_border_color $INACTIVE_COLOR
bspc config focused_border_color $PRIMARY_COLOR

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Wallpaper
feh --bg-scale ~/Pictures/wall.jpg &

# Polkit gnome
/usr/libexec/polkit-gnome-authentication-agent-1 &

# lauching polybar
$HOME/.config/polybar/launch.sh

